### ISSUE TITLE
Link incorreto no Passo 2 do processo de Download do JKD para Windows

### ISSUE THREAD

**Issue by moisescs** [cami-la/configuracao-inicial-ambiente-de-desenvolvimento-java#1]
Camila Boa Tarde!
No Passo 2 do processo de download do JDK para Windows tem link apontado direto para versão Linux o que fará com que o processo não funcione.
"2 Faça o Download do arquivo [.zip](https://cdn.azul.com/zulu/bin/zulu17.36.13-ca-jdk17.0.4-linux_x64.zip) (Azul Zulu: 17.0.4+8 x86 64-bit)"

**Comment by Mariaeeduarda** [comment]
Oi, eu baixei uma outra versao que acredito que vai dar no mesmo: Azul Zulu: 17.36.19
https://cdn.azul.com/zulu/bin/zulu17.36.19-ca-jdk17.0.4.1-win_i686.zip

**Comment by cami-la** [comment]
Acabei de corrigir, @moisescs. Muito obrigada pela observação! <3

Isso aí, @Mariaeeduarda. Já corrigi. Obrigadaaa. <3

**Comment by moisescs** [comment]
Muito Obrigado @cami-la
