### ISSUE TITLE
Erro no ao adicionar o swagger

### ISSUE THREAD

**Issue by JacksonJeanPS** [cami-la/configuracao-inicial-ambiente-de-desenvolvimento-java#3]
1- Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null

2- Execution failed for task ':SacolaApiApplication.main()'.
> Process 'command 'C:/Users/Jackson/.jdks/azul-17.0.4.1/bin/java.exe'' finished with non-zero exit value 1

Antes de adicionar o implementation 'io.springfox:springfox-boot-starter:3.0.0' não dava erro, e agora fica dando erro. 

Como corrigir.

Já reinstalei, já mudei o jdk, ja baixei o arquivo zulu de novo, ja fechei e abri, já reiniciei, já dei ctrl c + ctrl v nos arquivos aqui no git. e nada de corrigir. ME HELPAAAAAA

![Screenshot_13](https://user-images.githubusercontent.com/95863318/194158741-f2b34405-01c3-407d-9a48-6017b5d30fc2.png)

**Comment by cami-la** [comment]
Segue uma issue parecida com a sua: https://github.com/cami-la/sacola-api_IFOOD_DEV_WEEK/issues/16#issuecomment-1264342500
Caso ainda não conseguiu resolver, é só avisar que a gente tenta outra forma. (:
